#  Template pypi-publish

#  This template allows you to publish your python package, as defined in setup.py, to pypi.org.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The python package will be validated and published after the code is merged to master.

# Prerequisites: $PYPI_USERNAME and $PYPI_PASSWORD setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/pypi-publish/src/master/README.md

image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - pip install -r requirements.txt
              # install the current package
              - pip install -e .
              - pip install pytest
              - pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
              - pip install flake8
              - flake8 . --extend-exclude=dist,build --show-source --statistics
  branches:
    master:
      - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - pip install -r requirements.txt
              # install the current package
              - pip install -e .
              - pip install pytest
              - pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            # bump package version
            # - echo "__version__ = '1.0.${BITBUCKET_BUILD_NUMBER}'" > demo_pkg/__version__.py

            # Publish your python package to PyPI https://pypi.org/
            # See more details https://bitbucket.org/atlassian/pypi-publish/src/master
            - pipe: atlassian/pypi-publish:0.3.1
              variables:
                PYPI_USERNAME: soltus
                PYPI_PASSWORD: Et_xp.hZ2FD4BFU
                DISTRIBUTIONS: 'bdist_wheel'
                REPOSITORY: 'https://test.pypi.org/legacy/'
                FOLDER: 'src'